// Inline real-world manifest snippets used across parser tests.

export const PACKAGE_LOCK_V3 = JSON.stringify({
  name: "demo",
  version: "1.0.0",
  lockfileVersion: 3,
  requires: true,
  packages: {
    "": { name: "demo", version: "1.0.0", dependencies: { lodash: "^4.17.21" } },
    "node_modules/lodash": { version: "4.17.21" },
    "node_modules/chalk": { version: "5.3.0" },
    "node_modules/chalk/node_modules/ansi-styles": { version: "6.2.1" },
  },
});

export const PACKAGE_LOCK_V1 = JSON.stringify({
  name: "demo",
  version: "1.0.0",
  lockfileVersion: 1,
  dependencies: {
    lodash: { version: "4.17.21" },
    chalk: {
      version: "5.3.0",
      dependencies: {
        "ansi-styles": { version: "6.2.1" },
      },
    },
  },
});

export const YARN_LOCK_V1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-fake==

chalk@^5.0.0:
  version "5.3.0"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-5.3.0.tgz"
  integrity sha512-fake==
`;

export const PNPM_LOCK_V9 = `lockfileVersion: '9.0'

packages:

  lodash@4.17.21:
    resolution: {integrity: sha512-fake==}

  chalk@5.3.0:
    resolution: {integrity: sha512-fake==}

  '@types/node@20.14.0':
    resolution: {integrity: sha512-fake==}
`;

export const REQUIREMENTS_TXT = `# requirements for the demo app
-r common.txt
requests==2.31.0
flask[async]==3.0.0  ; python_version>="3.10"
git+https://github.com/example/lib.git@main
django==4.2.7
`;

export const POETRY_LOCK = `# This file is automatically generated by Poetry.
[[package]]
name = "requests"
version = "2.31.0"
description = "HTTP for humans."

[[package]]
name = "urllib3"
version = "2.0.7"
description = "HTTP client"
`;

export const PIPFILE_LOCK = JSON.stringify({
  _meta: { hash: { sha256: "x" } },
  default: {
    requests: { version: "==2.31.0" },
    urllib3: { version: "==2.0.7" },
  },
  develop: {
    pytest: { version: "==7.4.3" },
  },
});

export const UV_LOCK = `version = 1
requires-python = ">=3.10"

[[package]]
name = "anyio"
version = "4.2.0"

[[package]]
name = "click"
version = "8.1.7"
`;

export const GO_SUM = `github.com/davecgh/go-spew v1.1.1 h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=
github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/pkg/errors v0.9.1 h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=
github.com/pkg/errors v0.9.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
`;

export const CARGO_LOCK = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.35.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

export const GEMFILE_LOCK = `GEM
  remote: https://rubygems.org/
  specs:
    rake (13.1.0)
    rack (3.0.8)
    activesupport (7.1.2)
      base64
      concurrent-ruby (~> 1.0, >= 1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  rake
  rack
  activesupport (~> 7.1)

BUNDLED WITH
   2.4.10
`;

export const POM_XML = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>demo</artifactId>
  <version>1.0.0</version>
  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>6.1.2</version>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>32.1.3-jre</version>
    </dependency>
  </dependencies>
</project>
`;

export const GRADLE_LOCKFILE = `# This is a Gradle generated file for dependency locking.
# Manual edits can break the build and are not advised.
# This file is expected to be part of source control.
org.springframework:spring-core:6.1.2=compileClasspath,runtimeClasspath
com.google.guava:guava:32.1.3-jre=compileClasspath,runtimeClasspath
empty=
`;

export const COMPOSER_LOCK = JSON.stringify({
  "_readme": ["This file locks the dependencies"],
  "content-hash": "abc",
  packages: [
    { name: "monolog/monolog", version: "3.5.0" },
    { name: "psr/log", version: "3.0.0" },
  ],
  "packages-dev": [{ name: "phpunit/phpunit", version: "10.5.0" }],
});

export const PACKAGES_LOCK_JSON = JSON.stringify({
  version: 1,
  dependencies: {
    "net8.0": {
      "Newtonsoft.Json": { type: "Direct", resolved: "13.0.3" },
      "Serilog": { type: "Transitive", resolved: "3.1.1" },
    },
  },
});

export const CSPROJ = `<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog" Version="3.1.1" />
  </ItemGroup>
</Project>
`;
