import { writeFileSync } from "node:fs";
import * as path from "node:path";
import type { Finding, Severity } from "../../snitch-github/src/providers/types.js";

const HEADER = "# Snitch Security Scan";

export function writeMarkdown(
  findings: Finding[],
  meta: {
    fileCount: number;
    scanMode: string;
    provider: string;
    model: string;
    durationMs: number;
    repo: string;
    base: string | null;
  },
  outPath: string
): void {
  const lines: string[] = [];
  lines.push(HEADER);
  lines.push("");
  lines.push(
    `**${findings.length} finding${findings.length !== 1 ? "s" : ""}** in ${meta.fileCount} file${meta.fileCount !== 1 ? "s" : ""}.`
  );
  lines.push("");
  lines.push(
    `Repo: \`${meta.repo}\` | Base: \`${meta.base ?? "full-tree"}\` | Mode: \`${meta.scanMode}\` | Model: \`${meta.provider}/${meta.model}\` | Duration: ${(meta.durationMs / 1000).toFixed(1)}s`
  );
  lines.push("");

  if (findings.length === 0) {
    lines.push("No security issues found in the scanned files.");
  } else {
    const groups: Array<{ label: Severity; items: Finding[] }> = [
      { label: "Critical", items: findings.filter((f) => f.severity === "Critical") },
      { label: "High", items: findings.filter((f) => f.severity === "High") },
      { label: "Medium", items: findings.filter((f) => f.severity === "Medium") },
      { label: "Low", items: findings.filter((f) => f.severity === "Low") },
    ];

    for (const g of groups) {
      if (g.items.length === 0) continue;
      lines.push(`## ${g.label} (${g.items.length})`);
      lines.push("");
      for (const f of g.items) {
        const loc = f.line ? `${f.file}:${f.line}` : f.file;
        const tags = [f.cwe, f.owasp].filter(Boolean).join(" | ");
        lines.push(`### ${f.title}`);
        lines.push(`- **Location:** \`${loc}\``);
        if (tags) lines.push(`- **Reference:** ${tags}`);
        lines.push(`- **Risk:** ${f.risk}`);
        if (f.fix) lines.push(`- **Suggested fix:** ${f.fix}`);
        if (f.confidence) lines.push(`- **Confidence:** ${f.confidence}`);
        lines.push("");
      }
    }
  }

  lines.push("");
  lines.push("Generated by [Snitch](https://snitchplugin.com).");
  lines.push("");

  writeFileSync(outPath, lines.join("\n"), "utf-8");
}

export function writeSarif(sarifJson: string, outPath: string): void {
  writeFileSync(outPath, sarifJson, "utf-8");
}

export function reportPaths(cwd: string): {
  markdown: string;
  sarif: string;
} {
  return {
    markdown: path.resolve(cwd, "SECURITY_AUDIT_REPORT.md"),
    sarif: path.resolve(cwd, "SECURITY_AUDIT_REPORT.sarif"),
  };
}
