import { writeFileSync } from "node:fs";
import * as path from "node:path";
import type { Finding } from "./_shared/providers/types.js";
import { buildReportMarkdown } from "./_shared/report.js";

export function writeMarkdown(
  findings: Finding[],
  meta: {
    fileCount: number;
    scanMode: string;
    provider: string;
    model: string;
    durationMs: number;
    repo: string;
    base: string | null;
  },
  outPath: string
): void {
  // Use the same shared renderer as the GitHub Action so the on-disk
  // markdown matches what reviewers see in PR comments / the Action's
  // job summary. Adds a CLI-specific header line on top with repo/base.
  const head = `# Snitch Security Scan\n\nRepo: \`${meta.repo}\` · Base: \`${meta.base ?? "full-tree"}\`\n\n`;
  const body = buildReportMarkdown(findings, {
    fileCount: meta.fileCount,
    provider: meta.provider,
    model: meta.model,
    durationMs: meta.durationMs,
    scanType: meta.scanMode,
  });
  const tail = "\n---\nGenerated by [Snitch](https://snitchplugin.com).\n";
  writeFileSync(outPath, head + body + tail, "utf-8");
}

export function writeSarif(sarifJson: string, outPath: string): void {
  writeFileSync(outPath, sarifJson, "utf-8");
}

export function reportPaths(cwd: string): {
  markdown: string;
  sarif: string;
} {
  return {
    markdown: path.resolve(cwd, "SECURITY_AUDIT_REPORT.md"),
    sarif: path.resolve(cwd, "SECURITY_AUDIT_REPORT.sarif"),
  };
}
